// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetOmetro.Persistence;

namespace PetOmetro.Persistence.Migrations
{
    [DbContext(typeof(PetOmetroContext))]
    [Migration("20190728145209_Segunda")]
    partial class Segunda
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetOmetro.Domain.Domain.GeneroPet", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("GeneroPet");
                });

            modelBuilder.Entity("PetOmetro.Domain.Domain.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentário")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("DtNascimento");

                    b.Property<string>("Especie")
                        .HasMaxLength(64);

                    b.Property<int>("IdGeneroPet");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Raca")
                        .HasMaxLength(64);

                    b.Property<string>("UrlImagem")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("IdGeneroPet");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("PetOmetro.Domain.Domain.Pet", b =>
                {
                    b.HasOne("PetOmetro.Domain.Domain.GeneroPet", "GeneroPet")
                        .WithMany("Pets")
                        .HasForeignKey("IdGeneroPet")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
